include:
  - proxy.yaml

x-deploy: &deploy-dev
  deploy:
    resources:
      limits:
        cpus: "1"
        memory: 512M
      reservations:
        memory: 256M
x-env_file: &env_file
  env_file:
    - .env
x-restart: &restart
  restart: on-failure #no, on-failure , always(default), unless-stopped 


services:
  db:
    image: mysql:8
    <<: [*deploy-dev, *env_file, *restart]
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_HOST="%" # <--- Это вам обязательно понадобится при выполнении ДЗ!
    networks:
      backend:
        ipv4_address: 172.20.0.10
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql


  web:
    build:
      context: .
      dockerfile: Dockerfile.python
    restart: always
    environment:
      - DB_HOST=db
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
    depends_on: 
      - db
      - reverse-proxy
      - ingress-proxy
    ports: 
      - "5000:8090"
    networks: 
      backend:
        ipv4_address: 172.20.0.5

volumes:
  mysql_data:



